# Generated by Django 5.1.5 on 2025-02-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('I', 'Inicial'), ('P', 'Progreso'), ('F', 'Finalización')], max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.batch')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'db_table': 'events',
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='start_date_must_be_less_than_end_date'), models.CheckConstraint(condition=models.Q(models.Q(('batch__isnull', False), ('course__isnull', True)), models.Q(('batch__isnull', True), ('course__isnull', False)), _connector='OR'), name='exactly_one_batch_or_bootcamp'), models.CheckConstraint(condition=models.Q(('batch__isnull', False), ('category__in', ['I', 'F'])), name='initial_and_final_events_must_have_batch'), models.CheckConstraint(condition=models.Q(('course__isnull', False), ('category__in', ['I', 'P', 'F'])), name='course_events_can_only_be_initial_progress_or_final')],
            },
        ),
    ]
