# Generated by Django 5.1.5 on 2025-02-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_person_date_joined_person_first_name_person_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
    ]
